### ISSUE TITLE
State pollution with reused Matcher

### ISSUE THREAD

**Issue by Col-E** [tommyettinger/RegExodus#5]
I encountered a problem that seems to indicate there is state pollution between uses of a single `Matcher` instance.

To reproduce the issue I have this pattern and a matcher which will update the target `String` for each iteration of the loop. Every iteration gives the matcher a larger cut of the input string to attempt to match on. If I set the initial `i` to any value `<= 17` then the matcher will throw an exception at index `i==18`.
```java
Pattern pattern = new Pattern("^\\s*(?:(?:get|put)(?:static|field))\\s+({type}[\\w\\/]+)?(?:\\.({name}\\w+)?)?(?:\\s+({desc}[\\w\\/;]+))?\\s*$");
Matcher matcher = pattern.matcher();
String line = "  getstatic java...  ";
for (int i = 17; i < line.length() - 1; i++) {
	System.out.println(i);
	String s = line.substring(0, i);
	matcher.setTarget(s);
	matcher.setPosition(0);
	if (matcher.find()) {
		String type = matcher.group("type");
		String name = matcher.group("name");
		String desc = matcher.group("desc");
		System.out.println("Field " + type + "." + name + " " + desc);
	}
}
```
The exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: wrong findBackReg() target type :15
	at regexodus.Matcher.findBackReg(Matcher.java:2400)
	at regexodus.Matcher.search(Matcher.java:1802)
	at regexodus.Matcher.find(Matcher.java:496)
	at Demo.main(Demo.java:10)
```

## Workaround 1: Don't re-use the Matcher

If I change the example up a bit to this, then the problem goes away because we receive a new `Matcher` instance every time:
```java
Pattern pattern = new Pattern("^\\s*(?:(?:get|put)(?:static|field))\\s+({type}[\\w\\/]+)?(?:\\.({name}\\w+)?)?(?:\\s+({desc}[\\w\\/;]+))?\\s*$");
String line = "  getstatic java...  ";
for (int i = 17; i < line.length() - 1; i++) {
	System.out.println(i);
	String s = line.substring(0, i);
	Matcher matcher = pattern.matcher(s);
	if (matcher.find()) {
		String type = matcher.group("type");
		String name = matcher.group("name");
		String desc = matcher.group("desc");
		System.out.println("Field " + type + "." + name + " " + desc);
	}
}
```

## Workaround 2: Call `setPattern` instead of `setPosition` before each use

I also noticed that calling `setPattern(pattern)` resolves the issue, even though the same pattern is being used in each iteration.

**Comment by tommyettinger** [comment]
I'll investigate this... Regexodus is pretty much atrociously complicated internally, and I didn't write most of it, so large parts are still black boxes to me. Even the parts I did write are atrociously complicated in places, I'm just more likely to remember how they work...

**Comment by tommyettinger** [comment]
This turns out to have been a quick, if hard-to-understand, fix. I hadn't fiddled with Matcher's flush() method in a long time, possibly ever, and I don't know how it works. But, it was not resetting group 0 (which holds the entire match), and that seems to not be correct. Now all registers for groups are reset when flush() is called.
